### ISSUE TITLE
Update `/demo` to use latest release

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator-website#12]
The demo code in this site repo differs from the demo code that ships in the repository. We could consolidate them, so they match, but we should at least make sure the site's demo uses the latest (released, probably) Apache Annotator code--and maybe state the version in use?

**Comment by Treora** [comment]
Addressed in PR #13

**Comment by BigBlueHat** [comment]
#13 is merged, so closing. Great work @Treora!
