### ISSUE TITLE
Cleaning up post demo integration

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator-website#14]
When I run `yarn install` in the root of the repo it now creations an empty `node_modules/` file and an (essentially) empty `yarn.lock` file:
```yaml
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
```
So, how should we clean these up? `.gitignore` seems like a bad idea for `yarn.lock` (should we ever need to commit it) and magically deleting them during the `yarn install` run also seems like it'd throw off future developers.

💭's?

**Comment by Treora** [comment]
Oh, apparently I was using an older version of yarn, that does not
create yarn.lock nor node_modules when there are no dependencies.

I just updated yarn and committed the empty lock-file, seems the best
solution to me. And a .gitignore for node_modules, also created (empty).

We could instead have told people to run yarn in the submodule instead,
but quite likely we will have some dependencies at some moment anyway
(e.g. a static site generator to add headers and footers to every page).
