### ISSUE TITLE
Make `asf-site` the new `master`?

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator-website#2]
Right now the default git branch is `master`. The site, however, is published out of `asf-site`.

Do we want to:
a) use `asf-site` as our "prod" style branch (merge `master` into `asf-site` when it's "ready")
b) drop `master` and make `asf-site` the new default branch (everything else branches out of it)

I personally like option b. best, but a. can work too--as long as we make that clear and work it that way.

Thoughts? @apache/annotator-committers ?

**Comment by tilgovi** [comment]
I might prefer option (a). Opening a PR from master is pretty lightweight and maybe a good signal for "publish the website (y/n)?

**Comment by tilgovi** [comment]
Oh, asf-site is the default branch as far as GitHub is concerned and I've no way to change that. Maybe let's just delete master then.

**Comment by BigBlueHat** [comment]
Ah. Seems you're right. 👍 to deleting `master`...which I think Infra needs to do. Correct @Humbedooh?

**Comment by tilgovi** [comment]
Nope. I just did it. 🎉
