### ISSUE TITLE
Board report: January 2021

### ISSUE THREAD

**Issue by Treora** [apache/incubator-annotator-website#23]
Should go here: <https://cwiki.apache.org/confluence/display/INCUBATOR/January2021#annotator>

@BigBlueHat @tilgovi could you review, improve, and submit it?

--------------------
## Annotator

Annotator provides annotation enabling code for browsers, servers, and
humans.

Annotator has been incubating since 2016-08-30.

### Three most important unfinished issues to address before graduating:

  1. Communicate clear roadmap
  2. Add active contributors
  3. Demonstrate good governance through voting on process improvements.

### Are there any issues that the IPMC or ASF Board need to be aware of?

None.

### How has the community developed since the last report?

Community calls continue. A few new developers have reached out with interest in using and contributing to the project.

### How has the project developed since the last report?

Significant code reorganisation has been undertaken to generalise the selector algorithms, such that they could be applied to other document types/representations than the DOM. A performance issue has been resolved after feedback from early adopters.

### How would you assess the podling's maturity?
Please feel free to add your own commentary.

  - [x] Initial setup
  - [x] Working towards first release *(i.e. we made our first release)*
  - [x] Community building
  - [ ] Nearing graduation
  - [ ] Other:

### Date of last release:

  2020-07-11

### When were the last committers or PPMC members elected?

  2018-09-04

### Have your mentors been helpful and responsive?

As for a while only one mentor was active and responsive, Benjamin Young has been added as mentor to facilitate processes.

### Is the PPMC managing the podling's brand / trademarks?

Not applicable.

### Signed-off-by:

  - [ ] (annotator) Nick Kew  
     Comments:  
  - [ ] (annotator) Tommaso Teofili  
     Comments:  
  - [x] (annotator) Benjamin Young  
     Comments:

**Comment by tilgovi** [comment]
Added (with minor grammatical changes). Thank you, @Treora.
