### ISSUE TITLE
`yarn build` fails due to package path concatenation failure

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator-website#24]
Looks like a simple string/path concatenation problem (probably upstream in the demo code?):
"Module not found: Error: Can't resolve 'C:\Users\b\dev\apache\incubator-annotator-website\annotator\ **packagesdom** \src\index.ts' in 'C:\Users\b\dev\apache\incubator-annotator-website\annotator\web\demo'"
(see the bold bit above)

Raw error below...
```
ERROR in ./demo/index.js
Module not found: Error: Can't resolve 'C:\Users\b\dev\apache\incubator-annotator-website\annotator\packagesdom\src\index.ts' in 'C:\Users\b\dev\apache\incubator-annotator-website\annotator\web\demo'
 @ ./demo/index.js 26:0-273 90:23-53 91:26-59 92:19-49 190:32-46 238:19-39 247:19-36
 @ multi ./demo/index.html ./demo/index.js

ERROR in ../packages/dom/src/text-position/describe.ts
Module not found: Error: Can't resolve 'C:\Users\b\dev\apache\incubator-annotator-website\annotator\packagesselector\src\index.ts' in 'C:\Users\b\d...
```

**Comment by Treora** [comment]
I looked for all occurrences of `packages` in either repo; I expect it to follow from a mistake in our renaming magic that maps module names like `@apache-annotator/dom` to the local directory containing it (e.g. [here][1]). But I don’t see how any of those could cause the loss of a (back)slash. Perhaps some tool we use has a mistake in its conversion from forward to backward slashes, or something like that? May be hard to test without an MS Windows environment. Did our code work on Windows before?

[1]: https://github.com/apache/incubator-annotator/blob/b0a8028f3dd537169e78ff1aefcab05922bee061/babel.config.js#L61

**Comment by Treora** [comment]
This was fixed in https://github.com/apache/incubator-annotator/pull/105
