### ISSUE TITLE
Board Report: April 2024

### ISSUE THREAD

**Issue by reckart** [apache/incubator-annotator-website#40]
--------------------
## Annotator

Annotator provides annotation enabling code for browsers, servers, and
humans.

Annotator has been incubating since 2016-08-30.

### Three most important unfinished issues to address before graduating:

  1. Apache Annotator is unable to produce releases due to low activity
  2. PMC is largely inactive
  3. Motivation to contribute is low due to inability of producing enough release votes

### Are there any issues that the IPMC or ASF Board need to be aware of?

See above. Unless there is interest by new people to join the project and help getting out releases, IMHO it would make more sense to retire the podling, fork it and release it without the three-vote hurdle.

### How has the community developed since the last report?
 
The community has not grown.

### How has the project developed since the last report?

Yarn has been dropped from the project in favor of npm. Since then, a number of dependabot issues have piled up.

### How would you assess the podling's maturity?
Please feel free to add your own commentary.

  - [x] Initial setup
  - [x] Working towards first release
  - [ ] Community building
  - [ ] Nearing graduation
  - [x] Other: it is so stable that it is probably ready for retirement ;) 

### Date of last release:

  2021-07-14 (0.2.0)

We tried to get out a 0.3.0 in May 2022, but it got stuck in the vote.

### When were the last committers or PPMC members elected?

@reckart was the last one to join in August 2022 (waving the flag).

### Have your mentors been helpful and responsive?
@BigBlueHat has prepared the last incubator report for this project and has provided some guidance. 

### Is the PPMC managing the podling's brand / trademarks?
Are 3rd parties respecting and correctly using the podlings
name and brand? If not what actions has the PPMC taken to
correct this? Has the VP, Brand approved the project name?

I don't know.

### Signed-off-by:

  - [ ] (annotator) Nick Kew  
     Comments:  
  - [ ] (annotator) Tommaso Teofili  
     Comments:  
  - [x] (annotator) Benjamin Young  
     Comments:

**Comment by BigBlueHat** [comment]
@reckart sorry we missed getting the report in for April. Looks like [our new deadline is June 5th](https://lists.apache.org/thread/64njo3sd4fkrgwqnqqzkovnxwmp110yv). What you wrote above still holds true. A few folks had a chat on an issue in May...but that's hardly activity.

@tilgovi @Treora y'all OK with the board report above? It suggests we finally retire this--and likely move it back to where it should have stayed in the first place: here on GitHub...

The Apache Software Foundation seemed like the right place when we all worked for various companies contributing to annotation in different ways...that hasn't been the case for many years, and despite our eagerness on calls to dive back in and try again...it's clear we lack the off-call motivation.

Happy to discuss again (as ever), but not sure the outcome will/should differ from what @reckart has written.

If we're in agreement, any of us should be able to add it to https://cwiki.apache.org/confluence/display/INCUBATOR/June2024 before June 5th (@reckart that's how the Incubator does things vs. Whimsy).

Thanks, all,
🎩

**Comment by tilgovi** [comment]
If there's interest, I'm still happy to try to make a release! I definitely have ideas for next steps for the API but I've been hesitant.

Happy to organize a little hack day for us to do some work in real time.

**Comment by tbdinesh** [comment]
Yes please. Do. Thanks

**Comment by csarven** [comment]
Hey folks =) (Long journey of things to say the least..) FWIW, just wanted to say that I'm interested in re-visting annotation libraries for https://github.com/linkeddata/dokieli , and Apache Annotator will be the first thing I'll look closely. dokieli has its own annotator going but I'd like to replace as much of that possible with modular components that's community maintained. I don't want to make major promises here and I know that it may be too little (and too late) considering the history of the work here and what's needed to keep it "alive" but ideally anything that dokieli needs (improved or extended) can be made here / upstream. There are a bunch of other things that needs to be updated / replaced in dokieli (like the editor) so I'm looking at the annotator library in that context of an authoring + annotation tool.

**Comment by BigBlueHat** [comment]
Thank you, all. I've no objections to us continuing this work (inside or outside the ASF) we just need activity one way or the other.

Maybe let's do another call and create a road map with more folks involved?
________________________________

**Comment by reckart** [comment]
> Maybe let's do another call and create a road map with more folks involved? 

How long of a call would you suggest? A 30min-1h coordination call or rather
0.5-1 day workshop style hacking session?

**Comment by BigBlueHat** [comment]
@tilgovi not sure what you had in mind, but starting small seems prudent. Maybe an hour or at most two? Since you're likely running the show here, could you send out a scheduling link? Thanks!

**Comment by BigBlueHat** [comment]
Also, back on topic, the board report has been submitted at https://cwiki.apache.org/confluence/display/INCUBATOR/June2024

**Comment by reckart** [comment]
Folks, the next board report is over due:

> The board meeting is scheduled for Wed, 17 July 2024.
> The report for your podling will form a part of the Incubator PMC
> report. The Incubator PMC requires your report to be submitted 2 weeks
> before the board meeting, to allow sufficient time for review and
> submission **(Wed, July 03).**

**Comment by BigBlueHat** [comment]
Ugh...I've never understood the way these things bump into each other if you miss one previously.

I'll add the same one we did last month...albeit late.

Sorry folks.

**Comment by BigBlueHat** [comment]
Actually...since we're overdue (by 7 days...), I'm not going to gum up the gears. We'll see what they ask for next...

That said, we're clearly not coming out of our periodic dormancy very well...

Maybe let's take one more crack at a call/sync?

**Comment by CalvinKirs** [comment]
I'm glad to start this discussion. If there are any difficulties with the release process or if it's hard to get enough IPMC members to review and vote, I'm happy to help. Also, if you need a new mentor, I'd be glad to offer my services.

**Comment by reckart** [comment]
The current report deadline is: **Wed, August 07** - that is tomorrow.

**Comment by reckart** [comment]
I have opened a new issue for that report. https://github.com/apache/incubator-annotator-website/issues/41
