### ISSUE TITLE
Board Report: August 2024

### ISSUE THREAD

**Issue by reckart** [apache/incubator-annotator-website#41]
⏱️ **Deadline: 07 Aug 2024** 

--------------------
## Annotator

Annotator provides annotation enabling code for browsers, servers, and
humans.

Annotator has been incubating since 2016-08-30.

### Three most important unfinished issues to address before graduating:

  1. Apache Annotator is unable to produce releases due to low activity
  2. PMC is largely inactive
  3. Motivation to contribute is low due to inability of producing enough release votes

### Are there any issues that the IPMC or ASF Board need to be aware of?

See above. Unless there is interest by new people to join the project and help getting out releases, IMHO it would make more sense to retire the podling, fork it and release it without the three-vote hurdle.

### How has the community developed since the last report?
 
The community has not grown.

### How has the project developed since the last report?

Yarn has been dropped from the project in favor of npm. Since then, a number of dependabot issues have piled up.

There have been a few mails regarding potentially adding support for the [Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/Highlight) instead of using `mark` elements (while keeking the elements as a fallback).

### How would you assess the podling's maturity?
Please feel free to add your own commentary.

  - [x] Initial setup
  - [x] Working towards first release
  - [ ] Community building
  - [ ] Nearing graduation
  - [x] Other: it is so stable that it is probably ready for retirement ;) 

### Date of last release:

  2021-07-14 (0.2.0)

We tried to get out a 0.3.0 in May 2022, but it got stuck in the vote.

### When were the last committers or PPMC members elected?

@reckart was the last one to join in August 2022 (waving the flag).

### Have your mentors been helpful and responsive?
@BigBlueHat has prepared the last incubator report for this project and has provided some guidance. 

### Is the PPMC managing the podling's brand / trademarks?
Are 3rd parties respecting and correctly using the podlings
name and brand? If not what actions has the PPMC taken to
correct this? Has the VP, Brand approved the project name?

I don't know.

### Signed-off-by:

  - [ ] (annotator) Nick Kew  
     Comments:  
  - [ ] (annotator) Tommaso Teofili  
     Comments:  
  - [ ] (annotator) Benjamin Young  
     Comments:

**Comment by reckart** [comment]
@BigBlueHat @tilgovi @Treora Comments? Sign-offs?

**Comment by tilgovi** [comment]
I'm okay with this. I have put in some hours in the last month, removing Babel and trying to make the build a bit simpler. It's not there yet. I am interested in continuing the project at whatever pace, but happy to move it outside ASF if that's what folks want.

**Comment by reckart** [comment]
The thing is, we need to be able to make releases. It'd be great if we could do that at ASF - but we need three people to vote a +1. If we cannot muster that... well.

**Comment by reckart** [comment]
@CalvinKirs in case none of the current mentors sign off (@BigBlueHat @tteofili @niq) maybe you would like to?

**Comment by reckart** [comment]
> I'm okay with this. I have put in some hours in the last month, removing Babel and trying to make the build a bit simpler. It's not there yet. I am interested in continuing the project at whatever pace, but happy to move it outside ASF if that's what folks want.

Great! Could you please open an issue for this task in main repository and open a pull request (draft) with your current progress so the activity is visible?

**Comment by reckart** [comment]
I have added the report here: https://cwiki.apache.org/confluence/display/INCUBATOR/August2024

If one of the shepards would still like to tick their sign-off checkbox, please do it there as well: @BigBlueHat @tteofili @niq

If you do sign off, feel free my comment in the ipmc/shepards section regarding missing sign-offs.
