### ISSUE TITLE
Board Report: April 2019

### ISSUE THREAD

**Issue by BigBlueHat** [apache/incubator-annotator-website#7]
Due tomorrow: https://lists.apache.org/thread.html/7b14a304af0b4497d4729243c26bea7b3cd4bc7b19834c35793172d6@%3Cdev.annotator.apache.org%3E

To be submitted by adding it to this page: https://wiki.apache.org/incubator/April2019

```
Annotator

Annotator provides annotation enabling code for browsers, servers, and humans.

Annotator has been incubating since 2016-08-30.

Three most important unfinished issues to address before graduating:

 1. Release initial versions
 2. Add more active contributors
 3. Community growth in general

Any issues that the Incubator PMC (IPMC) or ASF Board wish/need to be
aware of?

  Community growth for our project has been much slower than expected. We are aiming
  to ship a release and add at least one committer prior to the next board report. We will
  also be discussing the project's scope and future and trying one last time to (re)build the
  interest and community we'd had during the W3C's Web Annotation Working Group days
  (and the time prior when Annotator.js and Open Annotation were in full swing). If there
  is anything else we should too to achieve incubator goals before the next board report,
  please let us know.

How has the community developed since the last report?

  The immediate Apache Annotator community has remained quiet,
  but interest in Web Annotations (and surrounding technology/specs)
  has increased. We hope to tap into some of that new activity in this
  second quarter of 2019. Additionally, we hope to do further community
  outreach in person at the upcoming I Annotate event in May:
  http://iannotate.org/

How has the project developed since the last report?

  Code and community show minimal (if any) progress. The projects focus
  may be too narrow or the audience for our current DOM libraries may be
  too small to achieve frequent activity at this point. We did begin an effort
  to expand the scope of the project slightly to include server-side code
  and Web Annotation Data Model testing, but interest so far has remained
  minimal.

How would you assess the podling's maturity?
Please feel free to add your own commentary.

  [x] Initial setup
  [-] Working towards first release
  [-] Community building
  [ ] Nearing graduation
  [ ] Other:

Date of last release:

  N/A

When were the last committers or PPMC members elected?

   Last committer was added in August. That same committer is now on the PMC as of November.

Have your mentors been helpful and responsive or are things falling
through the cracks? In the latter case, please list any open issues
that need to be addressed.

  We did welcome our two new mentors, but have not had follow-up
  conversations as a community to (re)focus the group since then. We
  hope to change that in the coming weeks as we look toward promoting
  the project again at the upcoming I Annotate 2019 conference.

Signed-off-by:

  [ ](annotator) Nick Kew
     Comments:
  [ ](annotator) Steve Blackmon
     Comments:
  [ ](annotator) Tommaso Teofili
     Comments:

IPMC/Shepherd notes:

```

@apache/annotator-committers would love your 👍's (or other) on the above. It's due tomorrow.

Thanks!
🎩

**Comment by tilgovi** [comment]
I would like to add an honest account to the "Any issues that the Incubator PMC..." section that states we are overdue for a release and that momentum has been slow. I would like to put a goalpost there that we aim for a release prior to I Annotate and that if we fail to generate interest this summer we should consider retiring.

**Comment by BigBlueHat** [comment]
@tilgovi I'll revise that shortly. My thought is to give ourselves (with board/mentor support/permission, I suppose) the window of time leading to the next board report--which is ~3 months. I Annotate should fall squarely in the middle of that, giving us a mid-point deadline for releasing something, an opportunity to promote and engage with others, and the hope of adding more committers following their contributions after the event.

Revision coming shortly. Thanks!

**Comment by BigBlueHat** [comment]
@apache/annotator-committers I've added this text to the "Any issues..." section:
>   Community growth for our project has been much slower than expected. We are aiming
  to ship a release and add at least one committer prior to the next board report. We will
  also be discussing the project's scope and future and trying one last time to (re)build the
  interest and community we'd had during the W3C's Web Annotation Working Group days
  (and the time prior when Annotator.js and Open Annotation were in full swing). If there
  is anything else we should too to achieve incubator goals before the next board report,
  please let us know.

I'm planning to submit this now, but if you need/want revisions, I'll try to watch for them and get them added to the required wiki page ASAP. Thanks, all!

**Comment by tilgovi** [comment]
I'd just scrap the last sentence. We don't need an open ended invitation for help. We're giving ourselves goals and we can ask mentors for advice.

**Comment by tilgovi** [comment]
Otherwise, perfect.

**Comment by BigBlueHat** [comment]
@tilgovi I made the tweak just now, so closing this one as complete. Thanks!
